sequenceDiagram
    actor User
    participant Artist
    participant Album
    participant Song

    User --> create_playlist(data)
    creat participant Playlist
    Playlist -->> User: add_to_playlist
    Playlist *-- add_song
    Playlist -->> User: add_song
