sequenceDiagram
    actor User
    participant Artist
    participant Album
    participant Song

User ->> Playlist: create_playlist(User, Song)
    create participant Playlist
    Playlist -->> User: add_to_playlist
    Playlist ->> Song: add_song
    Playlist -->> User: add_song
