sequenceDiagram
actor U as User
participant User
participant Artist
actor A as Artist

U->>User: subscribe_to(Artist)
User-->>U: successfully subscribed

A->>Artist: publish(Album)
Artist->>User: notify(Album)
User-->>U: push notification received
