---
config:
  layout: elk
---
classDiagram

    class User{
        +spoeudo
        +email
        +add_song()
        +add_playlist()
        +add_artist()
    }

    class Playlist{
        +name
    }

    class Artist{
        +name
    }

    classe Albume{
        +title
    }

    classe Song{
        +title
    }

    Artist "1" *-- "0..*" Album
    Album "1" *-- "1..*" Song
    User "1" -- "0..*" Artist
    Playlist "0..*" o-- "0..*" Song
