classDiagram

    class User{
        +String name
        +browse()
        +Playlist create_playlist()
        +add_to_library(Album)
        +subscribe_to(Artist)
    }

    class Artist{
        +String name
        +notify(User)
    }

    class Album{
        +String title
    }

    class Song{
        +String title
        +Byte[] data
    }

    class Playlist{
        +String name
        +add_song(Song)
        +remove_song(Song)
    }


Artist "1" *-- "0*" Album
Album "1" *-- "1*" Song
Playlist "1*" o-- "0*" Song
User --> Artist : Subscriber to
User "1" *-- "0*" Playlist
User "1" o-- "0*" Album : Personal Librairy
User "1" o-- "0*" Song : Personal Librairy
