sequenceDiagram
    actor User
    participant Library
    participant Book

    User ->> Library: create_loan(Book, User)
    Library ->> Book: mark_as_unavailable()
    create participant Loan
    Library ->> Loan: create_loan(Book, User)
    Library -->> User: loan created
